# Generated by Django 4.1.3 on 2022-12-12 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SushiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.CharField(max_length=120, unique=True, validators=[django.core.validators.MaxLengthValidator(2), django.core.validators.MaxLengthValidator(120)])),
                ('name', models.CharField(max_length=35, unique=True, validators=[django.core.validators.MaxLengthValidator(2), django.core.validators.MaxLengthValidator(35)])),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('category', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('ingredients', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(150)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sushi',
            },
        ),
    ]
