# Generated by Django 4.1.3 on 2022-12-12 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='imageUrl',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(2), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
