# Generated by Django 4.1.3 on 2022-12-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carmodel_auto_park'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='auto_park',
        ),
    ]
