# Generated by Django 4.1.3 on 2022-12-08 14:21

import apps.cars.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_carmodel_auto_park'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=apps.cars.services.upload_car_photo)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.carmodel')),
            ],
            options={
                'db_table': 'cars_photo',
            },
        ),
    ]
